package com.democracy.democracy_orchestrator.infrastructure.statemachine.events;

public enum PostulationEvents {
    VALIDATE_PERSON, SEND_RESULT_VALIDATED_PERSON,
    VALIDATE_PROFESSION,SEND_RESULT_VALIDATED_PROFESSION,
    VALIDATE_CRIMINAL_RECORDS, SEND_RESULT_CRIMINAL_RECORD_VALIDATED,
    VALIDATE_DOCUMENTS, SEND_RESULT_VALIDATE_DOCUMENT,
    OBTAIN_RESULT_VALIDATE_QUALIFICATIONS, SEND_RESULT_VALIDATE_QUALIFICATIONS,
    OBTAIN_RESULT_VALIDATE_DOCUMENT, COMPLETE, CANCEL;
}
