package com.democracy.democracy_orchestrator.infrastructure.statemachine.states;

public enum PostulationStates {
    NEW, PERSON_VALIDATED, IS_VALIDATED_PERSON,
    PROFESSION_VALIDATED, RESULT_PROFESSION_VALIDATED, IS_VALIDATE_PROFESSION,
    CRIMINAL_RECORDS_VALIDATED, RESULT_CRIMINAL_RECORDS_VALIDATED,IS_VALIDATED_RESULT_CRIMINAL_RECORD,
    QUALIFICATION_VALIDATED, RESULT_VALIDATE_QUALIFICATIONS, IS_VALIDATE_RESULT_QUALIFICATIONS,
    VALIDATE_DOCUMENT, RESULT_VALIDATE_DOCUMENT,IS_VALIDATED_DOCUMENTS,
    OBTAIN_RESULTS, COMPLETED, CANCELLED, NOT_VALID, ERROR;
}
