package com.democracy.democracy_orchestrator.infrastructure.statemachine.states;

public enum PostulationStates {
    NEW, PERSON_VALIDATED, PROFESSION_VALIDATED, CRIMINAL_RECORDS_VALIDATED, QUALIFICATION_VALIDATED, DOCUMENT_SEND_CHOICE,DOCUMENTS_CHOICE, DOCUMENTS_VALIDATED, COMPLETED, CANCELLED, NOT_VALID;
}
